// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rdBHDjzAyjou3ad6LR1wYo
// Component: oBqymgIo6n
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: pjkalEnQwi/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: rdBHDjzAyjou3ad6LR1wYo/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: oBqymgIo6n/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: SQURK6XwW3/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: 3NM9eEhLNY/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: z8vyjWcN4h/icon
import FaBrandsresearchgateIcon from "./icons/PlasmicIcon__FaBrandsresearchgate"; // plasmic-import: E1im7KV3HvW/icon
import CiborcidIcon from "./icons/PlasmicIcon__Ciborcid"; // plasmic-import: V_2bxxraAKW/icon
import Rectangle4Icon from "./icons/PlasmicIcon__Rectangle4"; // plasmic-import: 1Lyvr4Y_oN/icon
import ellipse2MYlCm2CJg from "./images/ellipse2.svg"; // plasmic-import: MYlCm2CJg/picture
import ellipse3AdaWFmcA from "./images/ellipse3.svg"; // plasmic-import: ada-wFmcA/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"homepage"}
              data-plasmic-override={overrides.homepage}
              className={classNames(defaultcss.all, sty.homepage)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__oewb7
                )}
              >
                {"Caroline Palavicino-Maggio, PhD"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1"}
                data-plasmic-override={overrides.frame1}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame1)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__jS9N7
                  )}
                >
                  {"About"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__rzFq6
                  )}
                >
                  {"Research"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__xihO
                  )}
                >
                  {"Publications"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__czCMp
                  )}
                >
                  {"Contact"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame2"}
                data-plasmic-override={overrides.frame2}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame2)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__tjr6P
                  )}
                >
                  {"Lab"}
                </div>
              </p.Stack>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__hj3Zq
                )}
              >
                {"Civil rights Activist\nNeuroscientist  Proud Latina"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__gjlrz
                )}
              >
                {"Post-doctoral fellow at Harvard University"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame3"}
                data-plasmic-override={overrides.frame3}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame3)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__vhMhh
                  )}
                >
                  {"More about me"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"clipNewSamplesForResearch1"}
                data-plasmic-override={overrides.clipNewSamplesForResearch1}
                className={classNames(
                  defaultcss.all,
                  sty.clipNewSamplesForResearch1
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___5QbbH
                )}
              >
                {"Identifying agression in female Drosophila"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___9WnLr
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet gravida risus ac velit odio. Tristique egestas iaculis fringilla pellentesque. Arcu magna eros, et egestas elementum eget. Eget ut massa aliquet imperdiet quam vulputate proin ullamcorper. At nec ornare penatibus vulputate pharetra, quis sit. Sed pulvinar viverra elementum id tellus integer convallis odio enim."
                }
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame7"}
                data-plasmic-override={overrides.frame7}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame7)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__xezW1
                  )}
                >
                  {"Read more"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(defaultcss.all, sty.rectangle6)}
              />

              <div
                data-plasmic-name={"rectangle8"}
                data-plasmic-override={overrides.rectangle8}
                className={classNames(defaultcss.all, sty.rectangle8)}
              />

              <div
                data-plasmic-name={"drosophila1"}
                data-plasmic-override={overrides.drosophila1}
                className={classNames(defaultcss.all, sty.drosophila1)}
              />

              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(defaultcss.all, sty.rectangle4)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__iVjGv
                )}
              >
                {"Hi, I’m Dr. Caroline Palavicino-Maggio"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__cFiKf
                )}
              >
                {"Research"}
              </div>

              <div
                data-plasmic-name={
                  "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster"
                }
                data-plasmic-override={
                  overrides.functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster
                }
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster
                )}
              >
                {
                  " Function and cellular localization of proteins in Drosophila melanogaster"
                }
              </div>

              <div
                data-plasmic-name={"rectangle7"}
                data-plasmic-override={overrides.rectangle7}
                className={classNames(defaultcss.all, sty.rectangle7)}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__m0LNk)}
                role={"img"}
                src={ellipse2MYlCm2CJg}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kSo1S
                )}
              >
                {
                  "I’m a neuroscientist who studies how the brain regulates aggressive behavior. In my current project, I am identifying and characterizing the brain cells that activate female aggression. \n\nI use the fruit fly model system because it allows us to control the activity of specific brain cells, and the genes those brain cells express—and then to infer whether or not that brain cell, region, or gene is involved in aggression."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__pD48
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet gravida risus ac velit odio. Tristique egestas iaculis fringilla pellentesque. Arcu magna eros, et egestas elementum eget. Eget ut massa aliquet imperdiet quam vulputate proin ullamcorper. At nec ornare penatibus vulputate pharetra, quis sit. Sed pulvinar viverra elementum id tellus integer convallis odio enim."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__t8Od
                )}
              >
                {"Selected Publications"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__uiAnk
                )}
              >
                {"Contact"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame6"}
                data-plasmic-override={overrides.frame6}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame6)}
              >
                <div
                  data-plasmic-name={"akarIconstwitterFill"}
                  data-plasmic-override={overrides.akarIconstwitterFill}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconstwitterFill
                  )}
                >
                  <GroupIcon
                    className={classNames(defaultcss.all, sty.svg___6Uegb)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"akarIconsfacebookFill"}
                  data-plasmic-override={overrides.akarIconsfacebookFill}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconsfacebookFill
                  )}
                >
                  <Group2Icon
                    className={classNames(defaultcss.all, sty.svg__zScjC)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"akarIconslinkedinFill"}
                  data-plasmic-override={overrides.akarIconslinkedinFill}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconslinkedinFill
                  )}
                >
                  <Group3Icon
                    className={classNames(defaultcss.all, sty.svg__aZN1)}
                    role={"img"}
                  />
                </div>

                <FaBrandsresearchgateIcon
                  className={classNames(defaultcss.all, sty.svg___09NtU)}
                  role={"img"}
                />

                <CiborcidIcon
                  className={classNames(defaultcss.all, sty.svg__uW2R9)}
                  role={"img"}
                />
              </p.Stack>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__mnn56
                )}
              >
                {
                  'Palavicino-Maggio, Caroline B.; Tobon, Krishna; Douard, Veronique; Ferraris, Ronaldo P.; Kuzhikandathil, Eldo V. (April 2011). "Effect of Clozapine on the Enteric System: Implications for Antipsychotic-Induced Weight Gain". The FASEB Journal. 25 (1 (supplement)). doi:10.1096/fasebj.25.1_supplement.lb390.\n\nPalavicino-Maggio, Caroline B.; Kuzhikandathil, Eldo V. (September 2016). "Dietary Fructose and GLUT5 Transporter Activity Contribute to Antipsychotic-Induced Weight Gain". Schizophrenia Bulletin. 42 (5): 1270–1279. doi:10.1093/SCHBUL/SBW037. PMC 4988743. PMID 27056716.\n\nPalavicino-Maggio, Caroline B.; Trannoy, Séverine; Holton, Kristina M.; Song, Xiaoying; Li, Kexin; Nevo, Eviatar (11 March 2019). "Aggression and courtship differences found in Drosophila melanogaster from two different microclimates at Evolution Canyon, Israel". Scientific Reports. 9 (1): 4084. Bibcode:2019NatSR...9.4084P. doi:10.1038/s41598-019-40701-8. PMC 6411990. PMID 30858499.\n\nPalavicino-Maggio, Caroline B.; Chan, Yick-Bun; McKellar, Claire; Kravitz, Edward A. (20 August 2019). "A small number of cholinergic neurons mediate hyperaggression in female Drosophila" (PDF). Proceedings of the National Academy of Sciences. 116 (34): 17029–17038. doi:10.1073/pnas.1907042116. PMC 6708353. PMID 31391301'
                }
              </div>

              <div
                data-plasmic-name={"drosophila2"}
                data-plasmic-override={overrides.drosophila2}
                className={classNames(defaultcss.all, sty.drosophila2)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame8"}
                data-plasmic-override={overrides.frame8}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame8)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__jMseU
                  )}
                >
                  {"Read more"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame9"}
                data-plasmic-override={overrides.frame9}
                hasGap={true}
                className={classNames(defaultcss.all, sty.frame9)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__uLgy
                  )}
                >
                  {"Send"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"component1"}
                data-plasmic-override={overrides.component1}
                className={classNames(defaultcss.all, sty.component1)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame10"}
                  data-plasmic-override={overrides.frame10}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame10)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__ggAOo
                    )}
                  >
                    {"Name"}
                  </div>

                  <div
                    data-plasmic-name={"rectangle9"}
                    data-plasmic-override={overrides.rectangle9}
                    className={classNames(defaultcss.all, sty.rectangle9)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame11"}
                  data-plasmic-override={overrides.frame11}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame11)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__amfI6
                    )}
                  >
                    {"Email"}
                  </div>

                  <div
                    data-plasmic-name={"rectangle10"}
                    data-plasmic-override={overrides.rectangle10}
                    className={classNames(defaultcss.all, sty.rectangle10)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame12"}
                  data-plasmic-override={overrides.frame12}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame12)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___0376U
                    )}
                  >
                    {"Subject"}
                  </div>

                  <div
                    data-plasmic-name={"rectangle11"}
                    data-plasmic-override={overrides.rectangle11}
                    className={classNames(defaultcss.all, sty.rectangle11)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame13"}
                  data-plasmic-override={overrides.frame13}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame13)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__bEkm3
                    )}
                  >
                    {"Message"}
                  </div>

                  <div
                    data-plasmic-name={"rectangle12"}
                    data-plasmic-override={overrides.rectangle12}
                    className={classNames(defaultcss.all, sty.rectangle12)}
                  />
                </p.Stack>
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div
              data-plasmic-name={"homepageMobile"}
              data-plasmic-override={overrides.homepageMobile}
              className={classNames(defaultcss.all, sty.homepageMobile)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___0Ne1W)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__oMtaK
                  )}
                >
                  {"Lab"}
                </div>
              </p.Stack>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__uUpwK
                )}
              >
                {"Civil rights Activist\nNeuroscientist  Proud Latina"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__roqfr
                )}
              >
                {"Post-doctoral fellow at Harvard University"}
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__zcUwp)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__w0QUl
                  )}
                >
                  {"More about me"}
                </div>
              </p.Stack>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__z2Koc
                )}
              >
                {"Identifying agression in female Drosophila"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___2UPws
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet gravida risus ac velit odio. Tristique egestas iaculis fringilla pellentesque. Arcu magna eros, et egestas elementum eget. Eget ut massa aliquet imperdiet quam vulputate proin ullamcorper. At nec ornare penatibus vulputate pharetra, quis sit. Sed pulvinar viverra elementum id tellus integer convallis odio enim."
                }
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__iZDt)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__qZvn8
                  )}
                >
                  {"Read more"}
                </div>
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.freeBox__q0Oxy)} />

              <div className={classNames(defaultcss.all, sty.freeBox__yR5X9)} />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <Rectangle4Icon
                  className={classNames(defaultcss.all, sty.svg___67FQh)}
                  role={"img"}
                />
              ) : null}

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__oedLs
                )}
              >
                {"Hi, I’m Dr. Caroline Palavicino-Maggio"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__s7HnQ
                )}
              >
                {"Research"}
              </div>

              <div
                data-plasmic-name={
                  "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2"
                }
                data-plasmic-override={
                  overrides.functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2
                }
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2
                )}
              >
                {
                  " Function and cellular localization of proteins in Drosophila melanogaster"
                }
              </div>

              <div className={classNames(defaultcss.all, sty.freeBox__mQpfj)} />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__m0VhR)}
                  role={"img"}
                  src={ellipse3AdaWFmcA}
                />
              ) : null}

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__dvBGl
                )}
              >
                {
                  "I’m a neuroscientist who studies how the brain regulates aggressive behavior. In my current project, I am identifying and characterizing the brain cells that activate female aggression. \n\nI use the fruit fly model system because it allows us to control the activity of specific brain cells, and the genes those brain cells express—and then to infer whether or not that brain cell, region, or gene is involved in aggression."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__q02Sb
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet gravida risus ac velit odio. Tristique egestas iaculis fringilla pellentesque. Arcu magna eros, et egestas elementum eget. Eget ut massa aliquet imperdiet quam vulputate proin ullamcorper. At nec ornare penatibus vulputate pharetra, quis sit. Sed pulvinar viverra elementum id tellus integer convallis odio enim."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__q6YoX
                )}
              >
                {"Selected Publications"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___2Zpw
                )}
              >
                {"Contact"}
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__nU39)}
              >
                <div
                  data-plasmic-name={"akarIconstwitterFill2"}
                  data-plasmic-override={overrides.akarIconstwitterFill2}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconstwitterFill2
                  )}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <GroupIcon
                      className={classNames(defaultcss.all, sty.svg__gTy28)}
                      role={"img"}
                    />
                  ) : null}
                </div>

                <div
                  data-plasmic-name={"akarIconsfacebookFill2"}
                  data-plasmic-override={overrides.akarIconsfacebookFill2}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconsfacebookFill2
                  )}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <Group2Icon
                      className={classNames(defaultcss.all, sty.svg__yyeOl)}
                      role={"img"}
                    />
                  ) : null}
                </div>

                <div
                  data-plasmic-name={"akarIconslinkedinFill2"}
                  data-plasmic-override={overrides.akarIconslinkedinFill2}
                  className={classNames(
                    defaultcss.all,
                    sty.akarIconslinkedinFill2
                  )}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <Group3Icon
                      className={classNames(defaultcss.all, sty.svg___6Xg8)}
                      role={"img"}
                    />
                  ) : null}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : false
                ) ? (
                  <FaBrandsresearchgateIcon
                    className={classNames(defaultcss.all, sty.svg__mrdVl)}
                    role={"img"}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : false
                ) ? (
                  <CiborcidIcon
                    className={classNames(defaultcss.all, sty.svg__iXeQk)}
                    role={"img"}
                  />
                ) : null}
              </p.Stack>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__eEoXs
                )}
              >
                {
                  'Palavicino-Maggio, Caroline B.; Tobon, Krishna; Douard, Veronique; Ferraris, Ronaldo P.; Kuzhikandathil, Eldo V. (April 2011). "Effect of Clozapine on the Enteric System: Implications for Antipsychotic-Induced Weight Gain". The FASEB Journal. 25 (1 (supplement)). doi:10.1096/fasebj.25.1_supplement.lb390.\n\nPalavicino-Maggio, Caroline B.; Kuzhikandathil, Eldo V. (September 2016). "Dietary Fructose and GLUT5 Transporter Activity Contribute to Antipsychotic-Induced Weight Gain". Schizophrenia Bulletin. 42 (5): 1270–1279. doi:10.1093/SCHBUL/SBW037. PMC 4988743. PMID 27056716.\n\nPalavicino-Maggio, Caroline B.; Trannoy, Séverine; Holton, Kristina M.; Song, Xiaoying; Li, Kexin; Nevo, Eviatar (11 March 2019). "Aggression and courtship differences found in Drosophila melanogaster from two different microclimates at Evolution Canyon, Israel". Scientific Reports. 9 (1): 4084. Bibcode:2019NatSR...9.4084P. doi:10.1038/s41598-019-40701-8. PMC 6411990. PMID 30858499.\n\nPalavicino-Maggio, Caroline B.; Chan, Yick-Bun; McKellar, Claire; Kravitz, Edward A. (20 August 2019). "A small number of cholinergic neurons mediate hyperaggression in female Drosophila" (PDF). Proceedings of the National Academy of Sciences. 116 (34): 17029–17038. doi:10.1073/pnas.1907042116. PMC 6708353. PMID 31391301'
                }
              </div>

              <div className={classNames(defaultcss.all, sty.freeBox__ku3El)} />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___8TPnT)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__e5HeR
                  )}
                >
                  {"Read more"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__xPw4C)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__bbf4
                  )}
                >
                  {"Send"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"component2"}
                data-plasmic-override={overrides.component2}
                className={classNames(defaultcss.all, sty.component2)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___3BCpb)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__tcWa8
                    )}
                  >
                    {"Name"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__qgCvs)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___1AfgG)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__oisBo
                    )}
                  >
                    {"Email"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__zlbe9)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__k8YjU)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__jYTdA
                    )}
                  >
                    {"Subject"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__vrirY)}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__nIhtD)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__g7Qfv
                    )}
                  >
                    {"Message"}
                  </div>

                  <div
                    className={classNames(defaultcss.all, sty.freeBox__dDjlC)}
                  />
                </p.Stack>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "homepage",
    "frame1",
    "frame2",
    "frame3",
    "clipNewSamplesForResearch1",
    "frame7",
    "rectangle6",
    "rectangle8",
    "drosophila1",
    "rectangle4",
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster",
    "rectangle7",
    "frame6",
    "akarIconstwitterFill",
    "akarIconsfacebookFill",
    "akarIconslinkedinFill",
    "drosophila2",
    "frame8",
    "frame9",
    "component1",
    "frame10",
    "rectangle9",
    "frame11",
    "rectangle10",
    "frame12",
    "rectangle11",
    "frame13",
    "rectangle12",
    "homepageMobile",
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2",
    "akarIconstwitterFill2",
    "akarIconsfacebookFill2",
    "akarIconslinkedinFill2",
    "component2"
  ],

  homepage: [
    "homepage",
    "frame1",
    "frame2",
    "frame3",
    "clipNewSamplesForResearch1",
    "frame7",
    "rectangle6",
    "rectangle8",
    "drosophila1",
    "rectangle4",
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster",
    "rectangle7",
    "frame6",
    "akarIconstwitterFill",
    "akarIconsfacebookFill",
    "akarIconslinkedinFill",
    "drosophila2",
    "frame8",
    "frame9",
    "component1",
    "frame10",
    "rectangle9",
    "frame11",
    "rectangle10",
    "frame12",
    "rectangle11",
    "frame13",
    "rectangle12"
  ],

  frame1: ["frame1"],
  frame2: ["frame2"],
  frame3: ["frame3"],
  clipNewSamplesForResearch1: ["clipNewSamplesForResearch1"],
  frame7: ["frame7"],
  rectangle6: ["rectangle6"],
  rectangle8: ["rectangle8"],
  drosophila1: ["drosophila1"],
  rectangle4: ["rectangle4"],
  functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster: [
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster"
  ],

  rectangle7: ["rectangle7"],
  frame6: [
    "frame6",
    "akarIconstwitterFill",
    "akarIconsfacebookFill",
    "akarIconslinkedinFill"
  ],

  akarIconstwitterFill: ["akarIconstwitterFill"],
  akarIconsfacebookFill: ["akarIconsfacebookFill"],
  akarIconslinkedinFill: ["akarIconslinkedinFill"],
  drosophila2: ["drosophila2"],
  frame8: ["frame8"],
  frame9: ["frame9"],
  component1: [
    "component1",
    "frame10",
    "rectangle9",
    "frame11",
    "rectangle10",
    "frame12",
    "rectangle11",
    "frame13",
    "rectangle12"
  ],

  frame10: ["frame10", "rectangle9"],
  rectangle9: ["rectangle9"],
  frame11: ["frame11", "rectangle10"],
  rectangle10: ["rectangle10"],
  frame12: ["frame12", "rectangle11"],
  rectangle11: ["rectangle11"],
  frame13: ["frame13", "rectangle12"],
  rectangle12: ["rectangle12"],
  homepageMobile: [
    "homepageMobile",
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2",
    "akarIconstwitterFill2",
    "akarIconsfacebookFill2",
    "akarIconslinkedinFill2",
    "component2"
  ],

  functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2: [
    "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2"
  ],

  akarIconstwitterFill2: ["akarIconstwitterFill2"],
  akarIconsfacebookFill2: ["akarIconsfacebookFill2"],
  akarIconslinkedinFill2: ["akarIconslinkedinFill2"],
  component2: ["component2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    homepage: makeNodeComponent("homepage"),
    frame1: makeNodeComponent("frame1"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    clipNewSamplesForResearch1: makeNodeComponent("clipNewSamplesForResearch1"),
    frame7: makeNodeComponent("frame7"),
    rectangle6: makeNodeComponent("rectangle6"),
    rectangle8: makeNodeComponent("rectangle8"),
    drosophila1: makeNodeComponent("drosophila1"),
    rectangle4: makeNodeComponent("rectangle4"),
    functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster:
      makeNodeComponent(
        "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster"
      ),

    rectangle7: makeNodeComponent("rectangle7"),
    frame6: makeNodeComponent("frame6"),
    akarIconstwitterFill: makeNodeComponent("akarIconstwitterFill"),
    akarIconsfacebookFill: makeNodeComponent("akarIconsfacebookFill"),
    akarIconslinkedinFill: makeNodeComponent("akarIconslinkedinFill"),
    drosophila2: makeNodeComponent("drosophila2"),
    frame8: makeNodeComponent("frame8"),
    frame9: makeNodeComponent("frame9"),
    component1: makeNodeComponent("component1"),
    frame10: makeNodeComponent("frame10"),
    rectangle9: makeNodeComponent("rectangle9"),
    frame11: makeNodeComponent("frame11"),
    rectangle10: makeNodeComponent("rectangle10"),
    frame12: makeNodeComponent("frame12"),
    rectangle11: makeNodeComponent("rectangle11"),
    frame13: makeNodeComponent("frame13"),
    rectangle12: makeNodeComponent("rectangle12"),
    homepageMobile: makeNodeComponent("homepageMobile"),
    functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2:
      makeNodeComponent(
        "functionAndCellularLocalizationOfProteinsInDrosophilaMelanogaster2"
      ),

    akarIconstwitterFill2: makeNodeComponent("akarIconstwitterFill2"),
    akarIconsfacebookFill2: makeNodeComponent("akarIconsfacebookFill2"),
    akarIconslinkedinFill2: makeNodeComponent("akarIconslinkedinFill2"),
    component2: makeNodeComponent("component2"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
